version: '3'

services:
    sspanel:
        image: sspaneluim/panel
        container_name: sspanel
        restart: always
        ports:
            - 80:80
        volumes:
            - ./config/.config.php:/var/www/config/.config.php
