version: '3'

services:
    sspanel:
        image: sspaneluim/panel
        container_name: sspanel
        restart: always
        ports:
            - 80:80
        volumes:
            - ./config/.config.php:/var/www/config/.config.php

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
